CREATE TABLE dosen (
  KD_DOSEN VARCHAR(6) PRIMARY KEY,
  NAMA_DOSEN VARCHAR(40),
  ALAMAT VARCHAR(40)
);

INSERT INTO dosen
  VALUES
    ('000001', 'EKO PURWANTO, M.Kom', 'SUKOHARJO'),
    ('000002', 'FAULINDA ELY NASTITI, M.Eng', 'SUKOHARJO'),
    ('000003', 'JONI MAULINDAR, M.Eng', 'SURAKARTA'),
    ('000004', 'SRI SUMARLINDA, M.Kom', 'YOGYAKARTA');

ALTER TABLE dosen
  DROP ALAMAT;
